"""add_tarot_tables

Revision ID: 0bacc69fd7b5
Revises: bd07a4bec1de
Create Date: 2026-01-28 22:37:08.514109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0bacc69fd7b5'
down_revision: Union[str, Sequence[str], None] = 'bd07a4bec1de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tarot_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=False, comment='英文名称，如 THE MAGICIAN'),
    sa.Column('name_zh', sa.String(), nullable=False, comment='中文名称，如 魔法师'),
    sa.Column('short_code', sa.String(), nullable=False, comment='短代码，如 ar01, wapa, cu02'),
    sa.Column('arcana', sa.String(), nullable=False, comment='大/小阿卡纳: major / minor'),
    sa.Column('suit', sa.String(), nullable=True, comment='花色: wands/cups/swords/pentacles (仅小阿卡纳)'),
    sa.Column('number', sa.Integer(), nullable=True, comment='数字: 1-14 (仅小阿卡纳)'),
    sa.Column('rank', sa.String(), nullable=True, comment='牌阶: ace/page/knight/queen/king 或数字'),
    sa.Column('image_filename', sa.String(), nullable=False, comment='图片文件名'),
    sa.Column('meaning_upright', sa.Text(), nullable=False, comment='正位含义'),
    sa.Column('meaning_reversed', sa.Text(), nullable=False, comment='逆位含义'),
    sa.Column('keywords_upright', sa.Text(), nullable=True, comment='正位关键词'),
    sa.Column('keywords_reversed', sa.Text(), nullable=True, comment='逆位关键词'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tarot_cards_short_code'), 'tarot_cards', ['short_code'], unique=True)
    op.create_table('tarot_readings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('spread_type', sa.String(), nullable=False, comment='牌阵类型: single/three_cards/celtic_cross/two_options/love_relationship/hexagram/horseshoe'),
    sa.Column('question', sa.Text(), nullable=True, comment='用户提问'),
    sa.Column('cards_drawn', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='抽到的牌，JSON数组格式'),
    sa.Column('interpretation', sa.Text(), nullable=True, comment='AI解读结果'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tarot_readings_created_at'), 'tarot_readings', ['created_at'], unique=False)
    op.create_index(op.f('ix_tarot_readings_spread_type'), 'tarot_readings', ['spread_type'], unique=False)
    op.create_index('ix_tarot_readings_user_created', 'tarot_readings', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_tarot_readings_user_id'), 'tarot_readings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tarot_readings_user_id'), table_name='tarot_readings')
    op.drop_index('ix_tarot_readings_user_created', table_name='tarot_readings')
    op.drop_index(op.f('ix_tarot_readings_spread_type'), table_name='tarot_readings')
    op.drop_index(op.f('ix_tarot_readings_created_at'), table_name='tarot_readings')
    op.drop_table('tarot_readings')
    op.drop_index(op.f('ix_tarot_cards_short_code'), table_name='tarot_cards')
    op.drop_table('tarot_cards')
    # ### end Alembic commands ###
