"""create_users_table

Revision ID: bd07a4bec1de
Revises: 
Create Date: 2026-01-28 22:26:42.385901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd07a4bec1de'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False, comment='用户唯一标识 (UUID)'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='邮箱地址（登录凭证）'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='密码哈希 (bcrypt)'),
    sa.Column('birth_date_encrypted', sa.LargeBinary(), nullable=True, comment='出生日期（AES-256-GCM 加密）'),
    sa.Column('birth_time_encrypted', sa.LargeBinary(), nullable=True, comment='出生时间（AES-256-GCM 加密）'),
    sa.Column('birth_place_encrypted', sa.LargeBinary(), nullable=True, comment='出生地点（AES-256-GCM 加密）'),
    sa.Column('gender', sa.String(length=10), nullable=True, comment='性别: male/female/other'),
    sa.Column('language', sa.String(length=5), nullable=False, comment='界面语言: zh/en'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
